# SRI Pool config
authority_public_key = "3VANfft6ei6jQq1At7d8nmiZzVhBFS4CiQujdgim1ign"
authority_secret_key = "7qbpUjScc865jyX2kiB4NVJANoC7GA7TAJupdzXWkc62"
cert_validity_sec = 3600
test_only_listen_adress_plain =  "0.0.0.0:34250"
listen_address = "0.0.0.0:34264"
# list of compressed or uncompressed pubkeys for coinbase payout (only supports 1 item in the array at this point)
coinbase_outputs = [
    "02e13cef1348924c49dd1f708bf38eb79ae4648c16f0301085f37547d1d25e33e0",
]

# Template Provider config
# local TP (this is pointing to localhost so you must run a TP locally for this configuration to work)
#tp_address = "127.0.0.1:8442"
# hosted testnet TP 
# tp_address = "89.116.25.191:8442"
# hosted regtest TP 
tp_address = "75.119.150.111:8442"

# SRI Pool JD config
listen_jd_address = "127.0.0.1:34264"
