Upstreams = [
    { channel_kind = "Extended", address = "127.0.0.1", port = 34254, pub_key = "3VANfft6ei6jQq1At7d8nmiZzVhBFS4CiQujdgim1ign"},
    # { channel_kind = "Group", address = "127.0.0.1", port = 34254, pub_key = "3VANfft6ei6jQq1At7d8nmiZzVhBFS4CiQujdgim1ign"},
]
listen_address = "127.0.0.1"
listen_mining_port = 34255
max_supported_version = 2
min_supported_version = 2
downstream_share_per_minute = 1
coinbase_reward_sat = 5_000_000_000
# This value is used by the proxy to communicate to the pool the expected hash rate when we open an
# extended channel, based on it the pool will set a target for the channel
expected_total_downstream_hr = 10_000
# If set to true the proxy will try to reconnect to an upstream that drop the connection
reconnect = true
