upstreams = [
    { channel_kind = "Group", address = "127.0.0.1", port = 34254, pub_key = "2di19GHYQnAZJmEpoUeP7C3Eg9TCcksHr23rZCC83dvUiZgiDL", jn_values = { address = "127.0.0.1", port = 34264, pub_key = "2di19GHYQnAZJmEpoUeP7C3Eg9TCcksHr23rZCC83dvUiZgiDL"}},
    { channel_kind = "Group", address = "127.0.0.1", port = 44254, pub_key = "2di19GHYQnAZJmEpoUeP7C3Eg9TCcksHr23rZCC83dvUiZgiDL", jn_values = { address = "127.0.0.1", port = 44264, pub_key = "2di19GHYQnAZJmEpoUeP7C3Eg9TCcksHr23rZCC83dvUiZgiDL"}},
    { channel_kind = "Group", address = "127.0.0.1", port = 54254, pub_key = "2di19GHYQnAZJmEpoUeP7C3Eg9TCcksHr23rZCC83dvUiZgiDL", jn_values = { address = "127.0.0.1", port = 54264, pub_key = "2di19GHYQnAZJmEpoUeP7C3Eg9TCcksHr23rZCC83dvUiZgiDL"}},
]
tp_address = "127.0.0.1:8442" 
listen_address = "127.0.0.1"
listen_mining_port = 34255
max_supported_version = 2
min_supported_version = 2
downstream_share_per_minute = 60
coinbase_reward_sat = 5_000_000_000
# This value is used by the proxy to communicate to the pool the expected hash rate when we open an
# extended channel, based on it the pool will set a target for the channel
expected_total_downstream_hr = 10_000
