coverage:
  status:
    project: off
    patch:   off

after_success:
  - bash <(curl -s https://codecov.io/bash)
  # Add retry logic
  - |
    if [ "$?" != "0" ]; then
      retries=0
      until [ "$retries" -ge 5 ]
      do
        sleep 10
        bash <(curl -s https://codecov.io/bash)
        if [ "$?" = "0" ]; then
          break
        fi
        retries=$((retries+1))
      done
    fi
