name = "stratum_v2"
version = "1.0.2"
authors = ["The Stratum v2 Developers"]
edition = "2021"
description = ""
documentation = "https://github.com/stratum-mining/stratum"
homepage = "https://stratumprotocol.org"
repository = "https://github.com/stratum-mining/stratum"
license = "MIT + Apache-2.0"
license-file = "LICENSE.md"
keywords = ["stratum", "mining", "bitcoin", "protocol"]

[workspace]
resolver="2"
members = [
    # Protocol Crates
    "stratum-protocols/v1",
    "stratum-protocols/v2/binary-sv2/serde-sv2",
    "stratum-protocols/v2/binary-sv2/no-serde-sv2/codec",
    "stratum-protocols/v2/binary-sv2/no-serde-sv2/derive_codec",
    "stratum-protocols/v2/binary-sv2/binary-sv2",
    "stratum-protocols/v2/noise-sv2",
    "stratum-protocols/v2/framing-sv2",
    "stratum-protocols/v2/codec-sv2",
    "stratum-protocols/v2/const-sv2",
    "stratum-protocols/v2/subprotocols/common-messages",
    "stratum-protocols/v2/subprotocols/template-distribution",
    "stratum-protocols/v2/subprotocols/mining",
    "stratum-protocols/v2/subprotocols/job-declaration",
    "stratum-protocols/v2/sv2-ffi",
    "stratum-protocols/v2/roles-logic-sv2",

    # Roles Crates
    "stratum-roles/mining-proxy",
    "stratum-roles/pool",
    "stratum-roles/test-utils/mining-device",
    "stratum-roles/test-utils/sv1-mining-device",
    "stratum-roles/translator",
    "stratum-roles/jd-client",
    "stratum-roles/jd-server",

    # Common Functionality
    "stratum-common",

    "benches",
]

[profile.dev]
# Required by super_safe_lock
opt-level = 1

[profile.test]
# Required by super_safe_lock
opt-level = 1

