[package]
name = "framing_sv2"
version = "0.1.3"
authors = ["fi3 <email@email.org>"]
edition = "2018"
description = "Sv2 frames"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
const_sv2 = { version = "0.1.0", path = "../../../protocols/v2/const-sv2"}
binary_sv2 = { version = "0.1.3", path = "../../../protocols/v2/binary-sv2/binary-sv2" }

[features]
