# SRI Pool config
authority_public_key = "3VANfft6ei6jQq1At7d8nmiZzVhBFS4CiQujdgim1ign"
authority_secret_key = "7qbpUjScc865jyX2kiB4NVJANoC7GA7TAJupdzXWkc62"
cert_validity_sec = 3600

# List of coinbase outputs used to build the coinbase tx
# ! Right now only one output is supported, so comment all the ones you don't need !
# For P2PK, P2PKH, P2WPKH, P2TR a BIP32 extended master public key is needed. For P2SH and P2WSH, a redeem script is needed. 
coinbase_outputs = [
    #{ output_script_type = "P2PK", output_script_value = "tpubDCZwvqywtAtGdoe2F9XM4zBfmTBcHgzpoTLvQCemacRUf9FEnpgr8fpgTSXLdkMnyTCBJ3gUiuAvVZ2KitTpNUEoFJei21sQXh7vbeu7px3" },
    #{ output_script_type = "P2PKH", output_script_value = "tpubDCZwvqywtAtGdoe2F9XM4zBfmTBcHgzpoTLvQCemacRUf9FEnpgr8fpgTSXLdkMnyTCBJ3gUiuAvVZ2KitTpNUEoFJei21sQXh7vbeu7px3" },
    #{ output_script_type = "P2SH", output_script_value = "00142ef89234bc95136eb9e6fee9d32722ebd8c1f0ab" },
    #{ output_script_type = "P2WSH", output_script_value = "00142ef89234bc95136eb9e6fee9d32722ebd8c1f0ab" },
    { output_script_type = "P2WPKH", output_script_value = "vpub5ZMie86usV2ZSrvUSoc3sLg9YM8cmE4xHVzhXudJhezGGoXQ8L6Hash7E4ucffBKZXXi4r5wLiCeouB4sTwSDkfivsbmFAGqvAv9Vt7k7Lg" },
    #{ output_script_type = "P2TR", output_script_value = "vpub5ZMie86usV2ZSrvUSoc3sLg9YM8cmE4xHVzhXudJhezGGoXQ8L6Hash7E4ucffBKZXXi4r5wLiCeouB4sTwSDkfivsbmFAGqvAv9Vt7k7Lg" },
]

# SRI Pool JD config
listen_jd_address = "0.0.0.0:34264"
# RPC config for mempool (it can be also the same TP if correctly configured)
core_rpc_url =  "http://127.0.0.1"
core_rpc_port = 18332
core_rpc_user =  "username"
core_rpc_pass =  "password"
