[package]
name = "integration-test"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoind = "0.36.0"
flate2 = "1.0.32"
minreq = { version = "2.12.0", features = ["https"] }
once_cell = "1.20.0"
tar = "0.4.41"

[lib]
path = "tests/common/mod.rs"
