[package]
name = "bip32_derivation"
version = "1.0.0"
edition = "2021"

[lib]
name = "bip32_derivation"
path = "src/lib.rs"

[[bin]]
name = "bin"
path = "src/main.rs"

[dependencies]
stratum-common = { path = "../../common" }
slip132 = "0.10"

[dev-dependencies]
toml = { version = "*", git = "https://github.com/diondokter/toml-rs", default-features = false, rev = "c4161aa" }