downstream_address = "0.0.0.0"
downstream_port = 34265

# Version support
max_supported_version = 2
min_supported_version = 2

# Minimum extranonce2 size for downstream
# Max value: 16 (leaves 0 bytes for search space splitting of downstreams)
# Max value for CGminer: 8
# Min value: 2
min_extranonce2_size = 8

# Withhold
withhold = true

# Auth keys for open encrypted connection downstream
authority_public_key = "3VANfft6ei6jQq1At7d8nmiZzVhBFS4CiQujdgim1ign"
authority_secret_key = "7qbpUjScc865jyX2kiB4NVJANoC7GA7TAJupdzXWkc62"
cert_validity_sec = 3600

# How many time the JDC try to reinitialize itself after a failure 
retry = 10

#tp_address = "127.0.0.1:8442"
# hosted testnet TP 
# tp_address = "89.116.25.191:8442"
# hosted regtest TP 
tp_address = "75.119.150.111:8442"

[[upstreams]]
authority_pubkey = "3VANfft6ei6jQq1At7d8nmiZzVhBFS4CiQujdgim1ign"
pool_address = "127.0.0.1:34254"
jd_address = "127.0.0.1:34264"

[[upstreams]]
authority_pubkey = "3VANfft6ei6jQq1At7d8nmiZzVhBFS4CiQujdgim1ign"
pool_address = "127.0.0.1:34254"
jd_address = "127.0.0.1:34264"
