[package]
name = "job_negotiation_sv2"
version = "0.1.0"
authors = ["fi3 <email@email.org>"]
edition = "2018"


[dependencies]
binary_sv2 = {version = "0.1.3", path = "../../../../protocols/v2/binary-sv2/binary-sv2" }
const_sv2 = {version = "0.1.0", path = "../../../../protocols/v2/const-sv2"}

[features]
