# Upstream connection information
upstream_address = "127.0.0.1"
upstream_port = 34254
upstream_authority_pubkey = "2di19GHYQnAZJmEpoUeP7C3Eg9TCcksHr23rZCC83dvUiZgiDL"

# Downstream connection information
downstream_address = "127.0.0.1"
downstream_port = 34255

# Version support
max_supported_version = 2
min_supported_version = 2
