[package]
name = "noise_sv2"
version = "0.1.1"
authors = ["fi3 <email@email.org>"]
edition = "2018"
description = "Sv2 noise"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snow = "0.8"
# TODO use crates.io repo as soon as a new version is issued (version 1.0.1 is not wirking)
# removed serde dependency from below package
ed25519-dalek = { git = "https://github.com/dalek-cryptography/ed25519-dalek", branch = "develop",features = ["rand", "alloc"], default-features = false }
bs58 = { version ="0.4.0", features = ["check"] }
bytes = "1.0.1"
rand = "0.7.3" 
const_sv2 = {version = "0.1.*", path = "../../../protocols/v2/const-sv2"}
buffer_sv2 = {version = "0.1.*", path = "../../../utils/buffer"}
binary_sv2 = { version = "0.1.3", path = "../../../protocols/v2/binary-sv2/binary-sv2" }
