on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Clippy Lint

jobs:
  clippy-check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          - macos-latest
          - ubuntu-latest
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl

    steps:
      - name: Install stable toolchain & components
        uses: actions/checkout@v2
        with:
          profile: minimal
          toolchain: 1.57.0
          override: true
          components: clippy

      - name: Cargo clippy lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings -A dead-code
