on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Lint

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          - macos-latest
          - ubuntu-latest
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl

    steps:
      - name: Install stable toolchain & components
        uses: actions/checkout@v2
        with:
          profile: minimal
          toolchain: 1.53.0
          override: true
          components: rustfmt, clippy

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Rust fmt lint
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Cargo clippy lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings -A dead-code
 
