on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

name: MSRV 1.75 Check

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust:
          - 1.75.0 # MSRV

    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1.2.0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Build Benches
        run: cargo build --manifest-path=benches/Cargo.toml
      - name: Build Protocols
        run: cargo build --manifest-path=stratum-protocols/Cargo.toml
      - name: Build Roles
        run: cargo build --manifest-path=stratum-roles/Cargo.toml
      - name: Build Utils
        run: cargo build --manifest-path=utils/Cargo.toml
