on:
  push:
    branches: [ main ]
  pull_request:
    brances: [ main ]

name: Check sv2.h file is up to date with commit

jobs:
  sv2_header_check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          - macos-latest
          - ubuntu-latest
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl

    steps:
      - uses: actions/checkout@v2

      - name: Run equality check
        run: |
          echo Running equality check on header file
          sh ./equality.sh
