on:
  push:
    branches: [ main ]
  pull_request:
    brances: [ main ]

name: Check sv2.h file is up to date with commit

jobs:
  sv2_header_check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          - ubuntu-latest
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl

    steps:
      - uses: actions/checkout@v2

      - name: Check sv2 header file is up to date with commit
        run: |
          echo Check sv2 header file is up to date with commit
          sh ./sv2-header-check.sh
